package com.TeamDeadlock.ExploreBangladesh.planner.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity representing an AI-generated smart travel plan
 * Stores complete itineraries generated by the AI engine
 * Separate from manual TravelPlan to maintain clean separation
 */
@Entity
@Table(name = "ai_generated_travel_plans", indexes = {
    @Index(name = "idx_ai_user_id", columnList = "user_id"),
    @Index(name = "idx_ai_destination", columnList = "destination"),
    @Index(name = "idx_ai_created_at", columnList = "created_at")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AIGeneratedTravelPlan {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "user_id", nullable = false)
    private String userId;

    @Column(name = "destination", nullable = false)
    private String destination;

    @Column(name = "duration_days", nullable = false)
    private Integer durationDays;

    @Column(name = "budget_tier", nullable = false)
    private String budgetTier; // budget, midrange, luxury

    @Column(name = "travel_style")
    private String travelStyle; // adventure, relaxation, cultural, family, solo

    @Column(name = "total_budget_estimate", precision = 12, scale = 2)
    private BigDecimal totalBudgetEstimate;

    /**
     * Complete EnhancedTravelPlanDTO serialized as JSON
     * Contains: daily itineraries, hotels, attractions, restaurants, 
     * transportation, budget breakdown, and insights
     */
    @Column(name = "plan_data", columnDefinition = "LONGTEXT")
    private String planData;

    @Column(name = "generated_at", updatable = false)
    private LocalDateTime generatedAt;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        if (generatedAt == null) {
            generatedAt = LocalDateTime.now();
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
