# Application name
spring.application.name=ExploreBangladesh

# H2 Database Configuration (in-memory)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Basic Security
spring.security.user.name=test
spring.security.user.password=test

# Geoapify API Configuration
geoapify.api.key=2a42881f098048d7ae41b52f7c540f33
geoapify.base-url=https://api.geoapify.com/v2/places

# Country settings
hotels.country.code=BD
hotels.country.name=Bangladesh
