package com.TeamDeadlock.ExploreBangladesh.planner.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.util.List;
import java.math.BigDecimal;

/**
 * DTO for a single day's itinerary generated by AI
 * Includes hourly breakdown of activities with specific times
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AIDailyItineraryDTO {

    private Integer dayNumber;

    private LocalDate date;

    private String dayTitle; // e.g., "Day 1: Arrival and City Exploration"

    private String summary; // Brief description of the day's activities

    private List<AIHourlyActivityDTO> activities;  // Renamed from hourlyActivities to match frontend expectation

    private String mealPlan; // Description of meals planned for the day

    private String travelTips; // Special tips for this day

    private BigDecimal estimatedDailyBudget; // Estimated cost for the day

    private String weatherExpectation; // Expected weather for this day

    private List<String> packingReminders; // Things to pack for this day's activities
}
