package com.TeamDeadlock.ExploreBangladesh.planner.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalTime;
import java.math.BigDecimal;

/**
 * DTO for a single activity with specific timing
 * Generated by AI for precise hourly breakdown of daily itinerary
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AIHourlyActivityDTO {

    private LocalTime startTime; // When the activity starts (e.g., 9:00 AM)

    private LocalTime endTime; // When the activity ends (e.g., 11:30 AM)

    private String activityName; // Name of the activity (e.g., "Visit Ancient Temple")

    private String description; // Detailed description

    private String location; // Where the activity takes place

    private Double latitude; // GPS latitude

    private Double longitude; // GPS longitude

    private String activityType; // attraction, meal, transport, leisure, shopping, etc.

    private String duration; // Human-readable duration (e.g., "2.5 hours")

    private String recommendations; // AI recommendations for this activity

    private BigDecimal estimatedCost; // Estimated cost for this activity

    private String bookingInfo; // Whether booking is required and how

    private String dressCode; // What to wear for this activity

    private String travelTime; // Time to reach this location from previous one

    private Integer visitationOrder; // Order of visit in the day (1, 2, 3, etc.)
}
